/**
 * ============================================================================
 * departmentService.js
 * ============================================================================
 *
 * Service Layer Module for Department Management
 *
 * Responsibility:
 * ----------------------------------------------------------------------------
 * Encapsulates all Firebase Firestore operations for the departments collection.
 * Provides a clean abstraction layer between UI components and Firestore database,
 * handling CRUD (Create, Read, Update, Delete) operations for department records
 * in the employee management system.
 *
 * Features:
 * ----------------------------------------------------------------------------
 * - Create new departments with automatic timestamps and metadata initialization
 * - Retrieve complete list of all departments from the database
 * - Update existing department records with selective field updates
 * - Delete department records (permanent removal)
 * - Automatic server-side timestamp management for audit trails
 * - User context tracking for created/updated records
 * - Consistent error handling and propagation
 *
 * Firestore Collection Structure:
 * ----------------------------------------------------------------------------
 * Collection: "departments"
 * Document Fields:
 *   - id: Auto-generated by Firestore
 *   - name: Department name (required)
 *   - description: Department description (optional)
 *   - status: "active" or other status values (default: "active")
 *   - managerId: Reference to department manager (null by default)
 *   - createdBy: User ID of creator (auto-populated)
 *   - createdAt: Server timestamp of creation (auto-generated)
 *   - updatedAt: Server timestamp of last update (auto-updated)
 *
 * Error Handling Strategy:
 * ----------------------------------------------------------------------------
 * - All functions throw errors for caller to handle and display
 * - Firebase errors are propagated up the call stack with full context
 * - Calling components are responsible for error display and user feedback
 *
 * Dependencies:
 * ----------------------------------------------------------------------------
 * - Firebase Firestore: collection, document manipulation, and query functions
 * - Firebase database configuration (firebaseConfig.js)
 * ============================================================================
 */

/**
 * Imports for Department Service
 *
 * Firebase Firestore Functions:
 * - collection: Creates a reference to a Firestore collection for document operations
 * - addDoc: Adds a new document to a collection with Firestore auto-generated ID
 * - serverTimestamp: Generates server-side timestamp for audit trail creation
 * - doc: Creates a reference to a specific Firestore document by collection and ID
 * - getDoc: Retrieves a single document from Firestore (returns DocumentSnapshot)
 * - getDocs: Retrieves all documents from a collection (returns QuerySnapshot)
 * - deleteDoc: Deletes a document from Firestore permanently
 * - updateDoc: Updates specific fields in an existing document (partial update)
 *
 * Local Dependencies:
 * - db: Firebase Firestore database instance configured in firebaseConfig.js
 */
import {
  collection,
  addDoc,
  serverTimestamp,
  doc,
  getDoc,
  getDocs,
  deleteDoc,
  updateDoc,
} from "firebase/firestore";
import { db } from "../../../../firebase/firebaseConfig";

/**
 * createDepartmentService
 *
 * Creates a new department record in the Firestore database with automatic
 * metadata initialization. Sets default values for status, manager assignment,
 * and audit timestamps to maintain data consistency and audit trails.
 *
 * Workflow:
 * 1. Accepts department data from calling component
 * 2. Enriches data with metadata (status, creator, timestamps)
 * 3. Adds document to Firestore with auto-generated ID
 * 4. Returns created document including the ID
 *
 * Auto-Populated Metadata:
 * - status: Set to "active" by default for new departments
 * - managerId: Initialized as null (to be assigned later)
 * - createdBy: User ID of the authenticated department creator
 * - createdAt: Server timestamp of creation (database server time)
 * - updatedAt: Server timestamp of initial creation (synchronized with createdAt)
 *
 * @async
 * @param {Object} departmentData - Department information payload to create
 * @param {string} departmentData.name - Department name (required, e.g., "Engineering")
 * @param {string} [departmentData.description] - Department description (optional)
 * @param {number} [departmentData.budget] - Department budget allocation (optional)
 * @param {Object} currentUser - Authenticated user object from Auth context
 * @param {string} currentUser.uid - Unique identifier of authenticated user for audit trail
 * @returns {Promise<Object>} Promise resolving to created department object
 * @returns {string} Returns.id - Auto-generated Firestore document ID
 * @returns {Object} Returns - All departmentData fields plus metadata fields
 * @throws {Error} Firebase error if document creation fails or database is unavailable
 */
export const createDepartmentService = async (departmentData, currentUser) => {
  try {
    const departmentsRef = collection(db, "departments");
    const firebaseData = {
      ...departmentData,
      status: "active",
      managerId: null,
      createdBy: currentUser.uid,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    };
    const docRef = await addDoc(departmentsRef, firebaseData);
    return {
      id: docRef.id,
      ...firebaseData,
    };
  } catch (error) {
    throw error;
  }
};
/**
 * deleteDepartmentService
 *
 * Permanently removes a department record from the Firestore database by its unique ID.
 * This operation is irreversible and completely removes all department data.
 *
 * Important Considerations Before Deletion:
 * - Verify no active employees or dependencies exist for this department
 * - Consider soft deletes (updating status field) instead of hard deletes
 * - Implement checks in calling component to prevent accidental deletion
 * - Cannot be recovered after execution
 *
 * @async
 * @param {string} departmentId - Unique Firestore document ID of the department to delete
 * @returns {Promise<void>} Promise that resolves when deletion is complete
 * @throws {Error} Firebase error if deletion fails (department not found, permission denied, etc.)
 */
export const deleteDepartmentService = async (departmentId) => {
  try {
    const docRef = doc(db, "departments", departmentId);
    await deleteDoc(docRef);
  } catch (error) {
    throw error;
  }
};
/**
 * updateDepartmentService
 *
 * Updates one or more fields of an existing department record in Firestore.
 * Implements partial update strategy - only specified fields are modified,
 * while other fields remain unchanged. Automatically updates the timestamp
 * to track when changes were made for audit trail purposes.
 *
 * Update Strategy (Partial Update):
 * - Only fields included in updatedData are modified
 * - All other document fields remain unchanged
 * - updatedAt timestamp is automatically refreshed on every update
 * - Ideal for selective field updates without affecting entire record
 *
 * Supported Update Fields:
 * - name: Department name
 * - description: Department description/details
 * - managerId: Assigned manager's user ID
 * - status: Current status ("active", "inactive", etc.)
 * - budget: Department budget allocation
 *
 * @async
 * @param {string} departmentId - Unique Firestore document ID of department to update
 * @param {Object} updatedData - Object containing fields to update
 * @param {string} [updatedData.name] - Updated department name
 * @param {string} [updatedData.description] - Updated department description
 * @param {string} [updatedData.managerId] - Updated manager ID assignment
 * @param {string} [updatedData.status] - Updated department status
 * @param {number} [updatedData.budget] - Updated budget allocation
 * @returns {Promise<Object>} Promise resolving to object with updatedFirebaseData field
 * @returns {Object} Returns.updatedFirebaseData - The data that was sent to update
 * @throws {Error} Firebase error if update fails (document not found, permission denied, etc.)
 */
export const updateDepartmentService = async (departmentId, updatedData) => {
  try {
    const docRef = doc(db, "departments", departmentId);
    const updatedFirebaseData = {
      ...updatedData,
      updatedAt: serverTimestamp(),
    };
    await updateDoc(docRef, updatedFirebaseData);
    return { updatedFirebaseData };
  } catch (error) {
    throw error;
  }
};
/**
 * getDepartmentsService
 *
 * Fetches all department records from the Firestore database and returns them
 * as an array with their unique Firestore document IDs included in each object.
 * This is the primary function for populating department lists and dropdowns.
 *
 * Data Retrieval Process:
 * 1. Creates reference to the "departments" collection
 * 2. Queries Firestore to fetch all documents in collection
 * 3. Maps query results to include document ID with each record
 * 4. Returns array of department objects with complete data
 *
 * Returned Data Structure:
 * Each returned object includes:
 * - id: Auto-generated Firestore document ID (primary key)
 * - name: Department name
 * - description: Department description
 * - status: Department status ("active", etc.)
 * - managerId: Assigned manager's user ID (or null)
 * - budget: Department budget (if set)
 * - createdBy: User ID of department creator
 * - createdAt: Timestamp of creation
 * - updatedAt: Timestamp of last update
 *
 * Performance Considerations:
 * - No filtering or pagination applied at service level
 * - Returns all departments in collection (use with caution for large datasets)
 * - Consider implementing pagination for better performance with many departments
 * - Consider adding query filters if dealing with thousands of departments
 *
 * @async
 * @returns {Promise<Array<Object>>} Array of all department objects with IDs
 * @returns {string} [].id - Unique Firestore document identifier for each department
 * @returns {string} [].name - Department name
 * @returns {string} [].status - Department status
 * @throws {Error} Firebase error if retrieval fails (connection error, permission denied, etc.)
 */
export const getDepartmentsService = async () => {
  try {
    const departmentsRef = collection(db, "departments");
    const querySnapshot = await getDocs(departmentsRef);
    return querySnapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }));
  } catch (error) {
    throw error;
  }
};
/**
 * getEmployeeService
 *
 * Retrieves employee records from the Firestore database. This function serves as the
 * primary accessor for fetching employee list data from the backend. Currently in
 * development stage with placeholder implementation.
 *
 * Purpose:
 * - Fetches all employee records from the "employeesList" collection
 * - Returns employee data for populating employee directories and listings
 * - Provides a centralized service layer for employee data retrieval
 *
 * Data Source:
 * - Collection: "employeesList" in Firestore database
 * - Returns: Array of employee objects with all employee fields
 *
 * TODO - Implementation Notes:
 * - Complete the getDocs() query to retrieve all employee documents
 * - Map results to include Firestore document ID in each employee object
 * - Consider adding filtering options for different employee statuses
 * - Implement pagination for large employee datasets
 * - Add error logging for debugging Firebase connection issues
 *
 * Expected Return Structure (when fully implemented):
 * - Array of employee objects with fields like:
 *   - id: Firestore document ID
 *   - firstName: Employee first name
 *   - lastName: Employee last name
 *   - email: Employee email address
 *   - department: Assigned department
 *   - employmentStatus: Current employment status
 *   - joiningDate: Date employee joined
 *   - salary: Employee salary information
 *
 * @async
 * @returns {Promise<Array<Object>>} Promise resolving to array of employee objects
 * @returns {string} [].id - Unique Firestore document identifier for each employee
 * @throws {Error} Firebase error if retrieval fails (connection error, permission denied, etc.)
 */
export const getEmployeeService = async () => {
  try {
      const employeeRef = collection(db, "employeesList");
      const employeeData = await getDocs(employeeRef);
      return employeeData.docs.map(emp => emp.data());
  } catch (error) {
    throw error;
  }
};
